
import React from "react";
import Layout from "@/components/Layout";
import { productCategories } from "@/data/productCategories";
import ProductGrid from "@/components/product/ProductGrid";
import CategoryHeader from "@/components/product/CategoryHeader";
import { motion } from "framer-motion";

const SmartBatteryPage = () => {
  // Get the smart battery category data directly by key
  const categoryData = productCategories["smart-battery"];
  
  // Animation variants
  const fadeIn = {
    initial: { opacity: 0, y: 20 },
    animate: { opacity: 1, y: 0 },
    transition: { duration: 0.6 }
  };
  
  return (
    <Layout>
      <div className="py-16 bg-black">
        <div className="container mx-auto px-4">
          <motion.div 
            className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-12 items-center"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5 }}
          >
            <motion.div {...fadeIn} transition={{ delay: 0.2 }}>
              <h1 className="text-3xl font-bold mb-4 text-white">{categoryData.title}</h1>
              <p className="text-lg mb-6 text-gray-300">{categoryData.description}</p>
              <div className="space-y-4">
                <div className="flex items-center gap-2">
                  <div className="h-2 w-2 rounded-full bg-voltly-green"></div>
                  <span className="font-medium text-white">Lower electricity bills</span>
                </div>
                <div className="flex items-center gap-2">
                  <div className="h-2 w-2 rounded-full bg-voltly-green"></div>
                  <span className="font-medium text-white">Energy independence</span>
                </div>
                <div className="flex items-center gap-2">
                  <div className="h-2 w-2 rounded-full bg-voltly-green"></div>
                  <span className="font-medium text-white">Backup power during outages</span>
                </div>
                <div className="flex items-center gap-2">
                  <div className="h-2 w-2 rounded-full bg-voltly-green"></div>
                  <span className="font-medium text-white">Compatible with solar systems</span>
                </div>
              </div>
            </motion.div>
            <motion.div 
              className="aspect-video w-full" 
              {...fadeIn}
              transition={{ delay: 0.4 }}
            >
              <iframe
                width="100%"
                height="100%"
                src="https://www.youtube.com/embed/ZWZ9u8iOlu0"
                title="Smart Battery Education Video"
                frameBorder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
                className="rounded-lg shadow-lg"
              ></iframe>
            </motion.div>
          </motion.div>

          <motion.div 
            className="mb-12"
            {...fadeIn}
            transition={{ delay: 0.6 }}
          >
            <h2 className="text-2xl font-bold mb-4 text-white">How Home Batteries Work</h2>
            <p className="mb-4 text-gray-300">
              Smart home batteries store excess energy generated by solar panels or from the grid during off-peak hours.
              This stored energy can be used when electricity rates are highest or during a power outage, providing
              reliable backup power.
            </p>
            <p className="text-gray-300">
              With our integrated system, you can monitor and control your energy usage through a user-friendly mobile
              app, optimizing your home's energy efficiency and potentially saving thousands on electricity bills.
            </p>
          </motion.div>

          <motion.h2 
            className="text-2xl font-bold mb-6 text-white"
            {...fadeIn}
            transition={{ delay: 0.8 }}
          >
            Available Smart Battery Systems
          </motion.h2>
          <ProductGrid products={categoryData.products} />
          
          <motion.div 
            className="mt-8 p-6 bg-gray-900 rounded-lg"
            {...fadeIn}
            transition={{ delay: 1 }}
          >
            <h3 className="text-xl font-bold mb-4 text-white">Financing Details</h3>
            <p className="text-gray-300 mb-2">Our smart battery systems come with flexible financing options:</p>
            <ul className="list-disc pl-5 text-gray-300 space-y-2">
              <li>7.5% added to total purchase price</li>
              <li>7.99% interest rate</li>
              <li>36-month standard term</li>
              <li>Take up to 20 years to pay off</li>
              <li>No early payment penalties</li>
            </ul>
            <p className="text-sm text-gray-400 mt-4">
              *Internal note: Financing over $10,000 allows consumer to take up to 20 years, and under $9,999 it's 15 years
            </p>
          </motion.div>
        </div>
      </div>
    </Layout>
  );
};

export default SmartBatteryPage;
