// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkcixjapcbkswmjkcrfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rY2l4amFwY2Jrc3dtamtjcmZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NjE3NjQsImV4cCI6MjA2MjMzNzc2NH0.OYmvMnDbRVygNEs_E06kKXqoBENXqmhZ_EgU4mcelsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);